### ISSUE TITLE
NonMatchingChecksumError for oxford_flowers102

### ISSUE THREAD

**Issue by aaronhma** [tensorflow/datasets#2053]
**Short description**
When

**Environment information**
* Operating System: macOS
* Python version: Conda Python 3.7.7
* `tfds-nightly
* `tensorflow 2.2.0

**Reproduction instructions**

```python
import tensorflow as tf
import tensorflow_datasets as tfds
import json
# ======
# Load the dataset with TensorFlow Datasets.
dataset, dataset_info = tfds.load('oxford_flowers102', with_info = True, as_supervised = True)

# Create a training set, a validation set and a test set.
training, testing, validation = dataset['train'], dataset['test'], dataset['validation']
```

**Link to logs**
```
NonMatchingChecksumError: Artifact https://www.robots.ox.ac.uk/~vgg/data/flowers/102/102flowers.tgz, downloaded to /Users/aaronma/tensorflow_datasets/downloads/robots.ox.ac.uk_vgg_flowers_102_102flowersoWedSp98maBn1wypsDib6T-q2NVbO40fwvTflmPmQpY.tgz.tmp.3a12a0ebc88c4d528dc1f1a15f3b4648/102flowers.tgz, has wrong checksum. This might indicate:
 * The website may be down (e.g. returned a 503 status code). Please check the url.
 * For Google Drive URLs, try again later as Drive sometimes rejects downloads when too many people access the same URL. See https://github.com/tensorflow/datasets/issues/1482
 * The original datasets files may have been updated. In this case the TFDS dataset builder should be updated to use the new files and checksums. Sorry about that. Please open an issue or send us a PR with a fix.
 * If you're adding a new dataset, don't forget to register the checksums as explained in: https://www.tensorflow.org/datasets/add_dataset#2_run_download_and_prepare_locally
```

**Expected behavior**
I expect the dataset to be downloaded without any checksum errors.

Any help with this would be appreciated! Thanks!

**Comment by vijayphoenix** [comment]
Hi @aaronhma,
The checksums were recently updated. See https://github.com/tensorflow/datasets/issues/1977
So, I think the problem is fixed.
Let me know if you face any issues.

**Comment by aaronhma** [comment]
@vijayphoenix Thanks for letting me know! I just regenerated the checksums locally for the dataset v2.1.1. But, when I download the dataset, TensorFlow Datasets automatically downloads v2.1.0. I'm including a full bug log:

```
WARNING: Logging before flag parsing goes to stderr.
W0525 08:25:37.335721 4540759488 dataset_builder.py:666] Found a different version of the requested dataset:
/Users/aaronma/tensorflow_datasets/oxford_flowers102/2.1.1
Using /Users/aaronma/tensorflow_datasets/oxford_flowers102/2.1.0 instead.

/Users/aaronma/Library/Python/3.7/lib/python/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
```

Thanks!

**Comment by aaronhma** [comment]
@vijayphoenix After some Googling, I just realized that the oxford_flowers dataset has been updated from 2.1.0 to 2.1.1. The reason this `NonMatchingChecksumError` occurs happens here: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/stable_versions.txt#L619, as TFDS still relies on v2.1.0, instead of 2.1.1.

**Comment by vijayphoenix** [comment]
@aaronhma The dataset was recently updated, hence the changes are only present in tfds-nightly.

The stable_versions.txt contains all the versions and configs of datasets when stable version like tdfs-3.1.0 was released.

**Comment by aaronhma** [comment]
@vijayphoenix Currently, I'm using `tfds-nightly`, but I still receive the `NonMatchingChecksumError`. Is there a way to fix this? Thanks!

**Comment by vijayphoenix** [comment]
Possible solutions:
https://github.com/tensorflow/datasets/issues/1977#issuecomment-623036343 and https://github.com/tensorflow/datasets/issues/1977#issuecomment-632105079

**Comment by aaronhma** [comment]
@vijayphoenix Thanks for the quick reply! After running these commands, there still is a `NonMatchingChecksumError`. Thanks!

**Comment by vijayphoenix** [comment]
@aaronhma I did not face any error. See [colab](https://colab.research.google.com/drive/1kdqmjjp-Omg3GfKO4FthubegCnJUrNqf).

Try removing both the dataset and tfds and reinstall them.

**Comment by aaronhma** [comment]
@vijayphoenix Thanks for helping me! I ran the scripts and it worked! Thanks again and have a great day!
