### ISSUE TITLE
Invalid Tensor Index 'ragged_flat_values'

### ISSUE THREAD

**Issue by hermannsblum** [tensorflow/datasets#2243]
**Short description**
I'm trying to add a new dataset. Serialization succeeded, but when loading the data, the error below occurs.

```
TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got 'ragged_flat_values'  
```
Detailed stacktrace below, the error happens in the deserialization.

**Environment information**
* Operating System: ubuntu 18.04
* Python version: 3.6
* `tensorflow-datasets`/`tfds-nightly` version: `tfds-nightly`
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tested on tensorflow 2.2.0 and 2.3.0

**Reproduction instructions**

```
https://github.com/hermannsblum/tf_datasets/blob/3dpw/tensorflow_datasets/human_pose/pose_3dpw.py
```

**Link to logs**

[stack trace](https://gist.github.com/hermannsblum/cb3fd7d9986c9d4cea8f7d55f1a0b446)

**Expected behavior**
The dataset to load, or an error at dataset building.

**Additional context**

**Comment by hermannsblum** [comment]
The cause of the bug turns out to be passing a `Sequence` instead of a `FeaturesDict` as the top level feature to `DatasetInfo`. Therefore:

- if features should always be encapsulated in a dict, this should be mentioned in the [guide](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).
- otherwise, this is a bug that should be fixed.

**Comment by Conchylicultor** [comment]
`Sequence({})` should be allowed at top-level feature, so this is likely a bug.

**Comment by kyamagu** [comment]
`Sequence(Scalar())` works, but `Sequence(Sequence(Scalar()))` fails

**Comment by buckleytoby** [comment]
I'm still experiencing this problem, here's how I construct my sequence:
```
feature_spec = tfds.features.Sequence(tfds.features.Text(), length=len(v))
```
where `v = ['test', 'ing']`
